version: "3.3"

services:
  api:
    build: .
    container_name: orchestrator_api
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks: [backend]

  db:
    image: mysql:8.0
    container_name: orchestrator_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: orchestrator
      MYSQL_USER: orch
      MYSQL_PASSWORD: orchpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks: [backend]

  pma:
    image: phpmyadmin:5
    container_name: orchestrator_pma
    restart: always
    depends_on: [db]
    environment:
      PMA_HOST: db
      PMA_USER: orch
      PMA_PASSWORD: orchpass
    ports:
      - "8080:80"
    networks: [backend]

  resources_api:
    build:
      context: ./resources_api
      dockerfile: Dockerfile
    container_name: resources_api
    restart: always
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: orch
      DB_PASSWORD: orchpass
      DB_NAME: orchestrator
    depends_on:
      - db
    volumes:
      - ./resources_api:/app/resources_api
    networks: [backend]

volumes:
  mysql_data:

networks:
  backend:
